FROM kubeflowkatib/pytorch-mnist-cpu:latest@sha256:ea99a9efee9c0af7b598f63bdc203ea4387d7ac9da1d175f0641735fc88d6791

# docker build -t vanessa/pytorch-mnist-cpu:usernetes .

COPY ./launch.sh /launch.sh
COPY ./main.py /main.py
