apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 6
  # We set tasks explicitly to 0 to get -N 6 for the submit command
  tasks: 0
  containers:
    # This is built from the container here
    # docker build -t vanessa/pytorch-mnist-cpu:usernetes .
  - image: vanessa/pytorch-mnist-cpu:usernetes@sha256:255c6722bbd324165a2d9d2d8ca933910ec0928a64faac09737ba7511a1ed0d8
    command: /bin/bash /launch.sh
