apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 1
  # We set tasks explicitly to 0 to get -N 1 for the submit command
  tasks: 0
  containers:
    # This is built from the container here
    # docker build -t vanessa/pytorch-mnist-cpu:usernetes .
  - image: vanessa/pytorch-mnist-cpu:usernetes@sha256:e1943ec68aaeb79c06017035abbe5d7bb5c7e4a4e28f39aac4b1d450396f744c
    command: /bin/bash /launch.sh
    resources:
      limits:
        cpu: "7"
      requests:
        cpu: "7"
