apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 6
  interactive: true
  containers:
  - image: vanessa/iperf3:usernetes
    resources:
      limits:
        cpu: "7"
      requests:
        cpu: "7"
